import { StyleSheet } from 'react-native';

export const createAccountScreenStyles = StyleSheet.create({
    page: { flex: 1, backgroundColor: '#f6f7fb' },
    container: { flexGrow: 1, padding: 20, justifyContent: 'center' },
    card: {
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 24,
        padding: 24,
        marginHorizontal: 16,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 20,
        shadowOffset: { width: 0, height: 8 },
    },
    topIcon: { 
        width: 72, 
        height: 72, 
        borderRadius: 18, 
        backgroundColor: '#c026d3', 
        alignItems: 'center', 
        justifyContent: 'center', 
        marginBottom: 12 
    },
    topIconGlyph: { color: '#fff', fontSize: 28, fontWeight: '800' },
    title: { fontSize: 28, fontWeight: '900', color: '#0f172a', marginBottom: 6, textAlign: 'center' },
    subtitle: { fontSize: 15, color: '#64748b', marginBottom: 16, textAlign: 'center' },
    errorText: { color: '#dc2626', fontSize: 14, marginBottom: 10, textAlign: 'center' },
    input: {
        width: '100%',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 12,
        padding: 14,
        marginBottom: 12,
        fontSize: 15,
        backgroundColor: '#ffffff',
        color: '#0f172a',
    },
    primaryBtn: { width: '100%', alignItems: 'center', marginTop: 4, marginBottom: 8 },
    primaryBtnDisabled: { opacity: 0.7 },
    primaryBtnText: { 
        color: '#fff', 
        fontSize: 16, 
        fontWeight: '900', 
        backgroundColor: '#c026d3', 
        paddingVertical: 14, 
        width: '100%', 
        textAlign: 'center', 
        borderRadius: 14 
    },
    inputError: { borderColor: '#ef4444' },
    fieldError: { width: '100%', color: '#ef4444', fontSize: 12, marginTop: -6, marginBottom: 8 },
    orText: { fontSize: 14, color: '#9ca3af', marginBottom: 10, textAlign: 'center' },
    socialContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginBottom: 20,
    },
    socialButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 12,
        padding: 12,
        width: '45%',
        justifyContent: 'center',
    },
    socialIcon: { width: 20, height: 20, marginRight: 10 },
    socialText: { fontSize: 15, color: '#0f172a' },
    footerText: { fontSize: 14, color: '#6b7280', textAlign: 'center' },
    loginLink: { color: '#c026d3', fontWeight: '900' },
});
