import { StyleSheet } from 'react-native';

export const orderScreenStyles = StyleSheet.create({
    page: { flex: 1, backgroundColor: '#ffffff' },
    container: { flexGrow: 1, padding: 20 },
    // Back button styles
    backButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 20,
        paddingTop: 50,
        backgroundColor: '#ffffff',
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
    },
    backButtonText: {
        fontSize: 16,
        color: '#c026d3',
        fontWeight: '600',
        marginLeft: 4,
    },
    card: {
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 24,
        padding: 24,
        marginHorizontal: 16,
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 20,
        shadowOffset: { width: 0, height: 8 },
    },
    hotelImage: {
        width: '100%',
        height: 200,
        borderRadius: 16,
        marginBottom: 20,
    },
    hotelInfo: {
        marginBottom: 20,
    },
    hotelName: {
        fontSize: 28,
        fontWeight: '900',
        color: '#0f172a',
        marginBottom: 8,
    },
    hotelType: {
        fontSize: 16,
        color: '#64748b',
        marginBottom: 4,
    },
    hotelAddress: {
        fontSize: 16,
        color: '#64748b',
        marginBottom: 12,
    },
    ratingContainer: {
        marginBottom: 16,
    },
    ratingText: {
        fontSize: 16,
        color: '#f59e0b',
        fontWeight: '600',
    },
    description: {
        fontSize: 15,
        color: '#64748b',
        lineHeight: 22,
        marginBottom: 16,
    },
    amenitiesContainer: {
        marginBottom: 20,
    },
    amenitiesTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#0f172a',
        marginBottom: 8,
    },
    amenitiesList: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    amenityTag: {
        backgroundColor: '#f0f9ff',
        borderWidth: 1,
        borderColor: '#0ea5e9',
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 6,
    },
    amenityText: {
        fontSize: 14,
        color: '#0ea5e9',
        fontWeight: '600',
    },
    subImagesTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#0f172a',
        marginBottom: 12,
    },
    subImagesWrapper: {
        marginBottom: 24,
    },
    subImagesContainer: {
        paddingRight: 20,
    },
    subImageContainer: {
        marginRight: 12,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: 'transparent',
        overflow: 'hidden',
    },
    subImageContainerSelected: {
        borderColor: '#c026d3',
        borderWidth: 3,
    },
    subImage: {
        width: 100,
        height: 100,
        borderRadius: 10,
    },
    bookingForm: {
        backgroundColor: '#f8fafc',
        borderRadius: 16,
        padding: 20,
        marginTop: 8,
    },
    formTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#0f172a',
        marginBottom: 20,
        textAlign: 'center',
    },
    inputGroup: {
        marginBottom: 16,
    },
    inputLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 8,
    },
    pickerButton: {
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 12,
        padding: 14,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        minHeight: 60,
    },
    pickerButtonContent: {
        flex: 1,
        marginRight: 8,
    },
    pickerButtonText: {
        fontSize: 16,
        color: '#0f172a',
        fontWeight: '600',
        marginBottom: 4,
    },
    pickerPriceText: {
        fontSize: 14,
        color: '#c026d3',
        fontWeight: '600',
    },
    pickerArrow: {
        fontSize: 12,
        color: '#9ca3af',
    },
    availableText: {
        fontSize: 14,
        color: '#10b981',
        marginTop: 4,
        fontWeight: '500',
    },
    dateRow: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 16,
    },
    dateGroup: {
        flex: 1,
    },
    dateButton: {
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 14,
        alignItems: 'center',
        minHeight: 60,
        justifyContent: 'center',
    },
    dateDayText: {
        fontSize: 20,
        color: '#0f172a',
        fontWeight: '700',
        textAlign: 'center',
        marginBottom: 2,
    },
    dateMonthYearText: {
        fontSize: 12,
        color: '#6b7280',
        textAlign: 'center',
        fontWeight: '500',
    },
    roomCountContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#f8fafc',
        borderWidth: 1,
        borderColor: '#e2e8f0',
        borderRadius: 16,
        paddingVertical: 8,
        paddingHorizontal: 16,
        maxWidth: 200,
        alignSelf: 'center',
    },
    roomCountButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#c026d3',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#c026d3',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    roomCountButtonDisabled: {
        backgroundColor: '#f1f5f9',
        shadowOpacity: 0,
        elevation: 0,
    },
    roomCountButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#ffffff',
    },
    roomCountButtonTextDisabled: {
        color: '#cbd5e1',
    },
    roomCountDisplay: {
        minWidth: 40,
        alignItems: 'center',
        paddingHorizontal: 8,
    },
    roomCountText: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1e293b',
    },
    totalContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#ffffff',
        borderRadius: 12,
        padding: 16,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: '#e5e7eb',
    },
    totalInfo: {
        flex: 1,
    },
    totalLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#0f172a',
        marginBottom: 4,
    },
    totalSubLabel: {
        fontSize: 12,
        color: '#6b7280',
    },
    totalPriceContainer: {
        alignItems: 'flex-end',
    },
    totalPrice: {
        fontSize: 18,
        fontWeight: '700',
        color: '#c026d3',
        lineHeight: 22,
    },
    totalCurrency: {
        fontSize: 12,
        color: '#6b7280',
        fontWeight: '500',
    },
    orderButton: {
        backgroundColor: '#c026d3',
        borderRadius: 14,
        paddingVertical: 16,
        alignItems: 'center',
    },
    orderButtonText: {
        color: '#ffffff',
        fontSize: 18,
        fontWeight: '700',
    },
    // Modal styles
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'flex-end',
        opacity: 1,
    },
    modalContent: {
        backgroundColor: '#ffffff',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        maxHeight: '70%',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#0f172a',
    },
    modalCloseButton: {
        width: 30,
        height: 30,
        borderRadius: 15,
        backgroundColor: '#f3f4f6',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalCloseText: {
        fontSize: 16,
        color: '#6b7280',
    },
    roomItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#f3f4f6',
    },
    roomItemSelected: {
        backgroundColor: '#f8fafc',
    },
    roomInfo: {
        flex: 1,
    },
    roomTypeText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#0f172a',
        marginBottom: 4,
    },
    roomPriceText: {
        fontSize: 14,
        color: '#c026d3',
        fontWeight: '600',
        marginBottom: 2,
    },
    roomAvailableText: {
        fontSize: 12,
        color: '#10b981',
    },
    checkmark: {
        fontSize: 16,
        color: '#c026d3',
        fontWeight: 'bold',
    },
    // Date Modal styles
    dateModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        opacity: 1,
    },
    dateModalContent: {
        backgroundColor: '#ffffff',
        borderRadius: 20,
        padding: 20,
        margin: 20,
        maxWidth: 400,
        width: '90%',
    },
    dateModalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    dateModalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#0f172a',
    },
    dateModalCloseButton: {
        width: 30,
        height: 30,
        borderRadius: 15,
        backgroundColor: '#f3f4f6',
        justifyContent: 'center',
        alignItems: 'center',
    },
    dateModalCloseText: {
        fontSize: 16,
        color: '#6b7280',
    },
});
